= SpringBoot Server <sec:springboot>

== Solution
As requested by the Assignment the API that interact with the PostgreSQL Database is written in Java using the SpringBoot framework which is specifically disgned, in addition to other things, to build Restful APIs
So we headed up to the Spring Initializer website and download the .zip file containing all the necessary dependencies for developing with SpringBoot

=== Design and Motivations
==== Dependencies:
 - *Spring Web:* First of all we need the Spring Web library to have all the necessary tools to build a REST API
 - *PostgreSQL Driver:* Because we need to interrogate a Database (PostgreSQL) we need the Java driver so we add it to the gradle dependencies
 - *Spring Data JPA:* Which simplifies the development of Spring-based applications requiring data source access. Built on the Java Persistence API (JPA)
 - *Lombok:* An annotation preprocessor that simplifies the creation of classes removing the need to write boilerplate code such as getters, setters, Constructors and overidded methods such as toString
 - *Spring Boot Actuator:* Equips the application with production ready featurs such as health, status, metrics and more, we added this because since we hosted the various parts of the Assignment in heroku for not having always the servers running in the backgroud of our laptops if we need to work only on the frontend or the banana_split server, with this dependency it is fast to check if there was an error on the server
 - *Swagger:* We used Swagger + Swagger UI for Documenting and testing the REST API

for the Design we opted for a *MVC* pattern offereb by default from SpringBoot Web:
 - *The Model layer:* Called entities and will be all the Java classes that represents the Database tables with all the fields and the relationships between the tables
 - *The Repository layer:* Consisting in the JPARepository and Service which contains all the logic to extract from the database all the requested data, in this part we will construct the queries with all the where clauses using Specifications and call the corresponding Repository method generated by the Java Persistence API (JPA) to execute the query on the database
 - *The Controller layer:* this part is where the endpoint is specified with all the input parameters and response logic

=== Implementation
==== Packages
We divided all the classes in packages for modularity:
 - *banana_bean package:* The main package where we will find the Main class and all the other packages
 - *config package:* In this package we will find all the classes for the necessary configurations more specifically:
    - *Cors configuration:* To allow the Cross Origin calls otherwise our endpoint could not be called from outside the hosting domain
    - *OpenAPI configuration:* To configure Swagger UI page
 - *utility package:* Containing the Utility class where are declared all the common functions, procedures, variables and constants used by all the other packeges
 - *entity package:* Containing the classes that represents the Database tables, fields and Relations between tables, in SpringBoot these are called Entities
 - *dto package:* Containing the DTO (Data Transfer Object) classes for the response, because sometimes we need a response that is different from the Entity representation
 - *repository package:* Containing all the Repository Interfaces for JPA to extract data from the DB
 - *specification_builders package:* Containing the static method for building Specifications (dynamic where clauses)
 - *service package:* Containing all the Service classes that construct all the Specifications, with the parameters got by the controllers, and build response object after calling the Repository function
 - *controller package:* Containing the Rest Controller endpoints that defines all the parameters accepted by the endpoint and manage the responses

==== How we connected the Entities to the PostgreSQL tables

==== Error handling

==== Validation of input parameters

==== DTOs usage

== Issues

=== DTOs issue

=== Entities issue

== Requirements

=== System Requirements

=== Necessary SpringBoot configuration

== Limitations

=== JPA Limitations